/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tietkiemcanhan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ldbl
 */
public class ThemMucTieu extends javax.swing.JFrame {
    int dem=1;
    String idMT="MT"+dem;
    String username="sa";
    String password="";
    String url="jdbc:sqlserver://localhost:1433;databaseName=QLTK;integratedSecurity=true";
    /**
     * Creates new form ThemMucTieu
     */
    public ThemMucTieu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTenMT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdo3thang = new javax.swing.JRadioButton();
        rdo6thang = new javax.swing.JRadioButton();
        rdo12thang = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tên mục tiêu:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        getContentPane().add(txtTenMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, -1));

        jLabel2.setText("Giá trị:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        getContentPane().add(txtGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, -1));

        jLabel3.setText("Thời gian:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        buttonGroup1.add(rdo3thang);
        rdo3thang.setText("3 tháng");
        getContentPane().add(rdo3thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 30));

        buttonGroup1.add(rdo6thang);
        rdo6thang.setText("6 tháng");
        getContentPane().add(rdo6thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 30));

        buttonGroup1.add(rdo12thang);
        rdo12thang.setText("12 tháng");
        getContentPane().add(rdo12thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 30));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            dem+=1;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, username, password);
            String query = "insert into studens (idMT,tenmuctieu,giatri,thoihan) values(?,?,?,?)";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1,idMT);
            st.setString(2,txtTenMT.getText());
            st.setString(3, txtGiaTri.getText());
            String th="";
            if(rdo3thang.isSelected()){
                th=rdo3thang.getText();
            }else if(rdo6thang.isSelected()){
                th=rdo6thang.getText();
            }else{
                th=rdo12thang.getText();
            }
            st.setString(4,th);
            JOptionPane.showMessageDialog(this,"Thêm mực tiêu thành công");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMucTieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMucTieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMucTieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMucTieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMucTieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rdo12thang;
    private javax.swing.JRadioButton rdo3thang;
    private javax.swing.JRadioButton rdo6thang;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtTenMT;
    // End of variables declaration//GEN-END:variables
int ham(){
    int ngay;
    if (rdo3thang.isSelected()) {
        ngay=90;
    } else if (rdo6thang.isSelected()) {
        ngay=180;
    }else{
        ngay=360;
    }
    return ngay;
}
}
